#!/bin/sh

STATUS_BUSY_FILE='/tmp/status_busy.txt'
STATUS_BUSY_UNTIL_FILE='/tmp/status_busy_until.txt'

case "${SSH_ORIGINAL_COMMAND}" in
  available)
    rm -f "${STATUS_BUSY_FILE}"
    rm -f "${STATUS_BUSY_UNTIL_FILE}"
    ;;
  busy\ *\ until\ *)
    printf "%s" "${SSH_ORIGINAL_COMMAND}" \
      | sed 's/busy \(.*\) until .*/\1/' \
      > "${STATUS_BUSY_FILE}"
    printf "%s" "${SSH_ORIGINAL_COMMAND}" \
      | sed 's/busy .* until \(.*\)/\1/' \
      > "${STATUS_BUSY_UNTIL_FILE}"
    ;;
  busy\ *)
    printf "%s" "${SSH_ORIGINAL_COMMAND}" \
      | sed 's/busy \(.*\)/\1/' \
      > "${STATUS_BUSY_FILE}"
    rm -f "${STATUS_BUSY_UNTIL_FILE}"
    ;;
  *)
    exit 1
esac
